# Generated by Django 4.2.6 on 2023-10-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenInfo',
            fields=[
                ('canteen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('canteen_name', models.CharField(blank=True, max_length=20, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canteen_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'customer_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.canteeninfo')),
            ],
            options={
                'db_table': 'manager_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MerchatInfo',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'merchat_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('user_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.customerinfo')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.managerinfo')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.merchatinfo')),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
    ]
