# Generated by Django 4.2.6 on 2023-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineInfo',
            fields=[
                ('cuisine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cuisine_price', models.FloatField(blank=True, null=True)),
                ('cuisine_photo', models.TextField(blank=True, null=True)),
                ('cuisine_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cuisine_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_num', models.IntegerField()),
            ],
            options={
                'db_table': 'order_context',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=5, null=True)),
                ('order_state', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=20, null=True)),
                ('store_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'store_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='canteeninfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='managerinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='merchatinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
