# Generated by Django 4.2.6 on 2023-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenInfo',
            fields=[
                ('canteen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('canteen_name', models.CharField(blank=True, max_length=20, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canteen_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuisineInfo',
            fields=[
                ('cuisine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cuisine_price', models.FloatField(blank=True, null=True)),
                ('cuisine_photo', models.TextField(blank=True, null=True)),
                ('cuisine_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cuisine_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'customer_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'manager_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchatInfo',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'merchat_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_num', models.IntegerField()),
            ],
            options={
                'db_table': 'order_context',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=5, null=True)),
                ('order_state', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=20, null=True)),
                ('store_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'store_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('user_tel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
